### PR TITLE
Corrected intersection methods

### LINKED ISSUE #250: Ray LineSegment intersection incorrect
```
public Coordinate intersection(LineSegment line) {
    Coordinate intersection = lineIntersection(line);

    if (intersection != null && inRay(intersection)) {
        return intersection;
    }

    return null;
}
```
This method does not work correctly.
Change the method to the following:
```
/**
 * Intersect ray with {@link LineSegment}
 *
 * @param lineSegment segment to intersect ray with
 * @return intersection between segment and ray, if there is none: null
 */
@Override
public Coordinate intersection(LineSegment lineSegment) {
    Coordinate intersection = lineIntersection(lineSegment);

    if (intersection != null && inRay(intersection)) {
        double factor = lineSegment.projectionFactor(intersection);
        if (factor >= 0 && factor <= 1.0) {
            return intersection;
        }
    }
    return null;
}
```

With `projectionFactor`, the `inRay()` method can also be changed to:

```
public boolean inRay(Coordinate coordinate) {
    return coordinate != null && projectionFactor(coordinate) >= 0;
}
```

### PR DESCRIPTION
**Pull request by jotoh98**
Not even my submitted solution in issue #250 was not correct. I added unit tests.
Fixes #250

### CODE REVIEW

File: src/main/java/com/treasure/hunt/utils/JTSUtils.java [hunk 1]
```diff
@@ -24,6 +24,8 @@
      */
     public static final GeometryFactory GEOMETRY_FACTORY = new GeometryFactory(new PrecisionModel(1000000000));
 
+    public static final double DISTANCE_ZERO = 1e-10;
```
Comment (rank-and-file) [inline src/main/java/com/treasure/hunt/utils/JTSUtils.java]: There already is a method called JTSUtils.doubleEqual(a,b) which can be used to achieve the same thing 
(When checking if x equals zero one can call JTSUtils.doubleEqual(x,0) and the method rounds x on the grid of the precision model of the GEOMETRY_FACTORY to determine wether the value is 0 or not).
You can manipulate the value in the construction of the PrecisionModel to get lower precision (use a lesser value then instead)

Comment (jotoh98) [reply src/main/java/com/treasure/hunt/utils/JTSUtils.java]: Thank you for pointing that out, I didn't know that. Of course, I've implemented these changes directly.

File: src/main/java/com/treasure/hunt/jts/geom/HalfPlane.java [hunk 2]
```diff
@@ -194,7 +155,12 @@ private Polygon toPolygon(CanvasBoundary boundary) {
...
 
-    public boolean equals(HalfPlane other) {
-        return p0.equals2D(other.p0) && p1.equals2D(other.p1);
+    @Override
+    public boolean equals(Object o) {
+        if (o instanceof HalfPlane) {
+            HalfPlane other = (HalfPlane) o;
+            return p0.equals2D(other.p0) && p1.equals2D(other.p1);
+        }
+        return false;
```
Comment (1-alex98) [inline src/main/java/com/treasure/hunt/jts/geom/HalfPlane.java]: u could use loombok for that

Comment (1-alex98) [reply src/main/java/com/treasure/hunt/jts/geom/HalfPlane.java]: also because the hashcode method should then also be adapted

**Review by 1-alex98 — DISMISSED** [review]

File: src/main/java/com/treasure/hunt/jts/geom/HalfPlane.java (hunk 2 above)
Comment (jotoh98) [reply src/main/java/com/treasure/hunt/jts/geom/HalfPlane.java]: Added `@EqualsAndHashCode(callSuper = false)` with param because of the warning

`Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.`

Comment (1-alex98) [reply src/main/java/com/treasure/hunt/jts/geom/HalfPlane.java]: You know tho that the annotation you have know is different from what you had before if you do not specify what fields are supposed to be compared. idk or maybe just go back to your custom implementation.

File: src/test/java/com/treasure/hunt/jts/geom/HalfPlaneTest.java [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+
+class HalfPlaneTest {
+
+    @Test
+    void test() {
+        HalfPlane halfPlane = new HalfPlane(new Coordinate(0, 0), new Coordinate(1, 0));
+        IntStream.range(0, 50)
+                .mapToObj(value -> new Coordinate(-10 + Math.random() * 20, Math.random() * 20))
+                .forEach(coordinate ->
+                        Assertions.assertFalse(halfPlane.inside(coordinate))
```
Comment (DorianRec) [inline src/test/java/com/treasure/hunt/jts/geom/HalfPlaneTest.java:17]: This test is not always correct.
With low probability, Math.random() could return 0,
causing a Coordinate(-10 + Math.random(), 0) being inside the halfplane.
In this case, the test will fail.

**Review by DorianRec — DISMISSED** [review]

**Review by DorianRec — APPROVED** [review]
