### PR TITLE
HinterStrategy: JavaDoc, More Preferences

### LINKED ISSUE #234: Bug in MaxAreaAngularHintStrategy
Simulating a game with NaiveAngleSearcher and MaxAreaAngularHintStrategy, i got this exception, caused by the MaxAreaAngularHintStrategy instantiating a LineString containing one point.

Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Invalid number of points in LineString (found 1 - must be 0 or >= 2)
	at org.locationtech.jts.geom.LineString.init(LineString.java:82)
	at org.locationtech.jts.geom.LineString.<init>(LineString.java:72)
	at org.locationtech.jts.geom.GeometryFactory.createLineString(GeometryFactory.java:582)
	at org.locationtech.jts.geom.GeometryFactory.createLineString(GeometryFactory.java:573)
	at com.treasure.hunt.strategy.hider.impl.MaxAreaAngularHintStrategy.move(MaxAreaAngularHintStrategy.java:367)
	at com.treasure.hunt.strategy.hider.impl.MaxAreaAngularHintStrategy.move(MaxAreaAngularHintStrategy.java:34)
	at com.treasure.hunt.game.GameEngine.hiderMove(GameEngine.java:124)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:114)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:168)
	at com.treasure.hunt.game.GameManager.lambda$beat$10(GameManager.java:261)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

### LINKED ISSUE #284: Operation does not support GeometryCollection arguments
Bug in Statistical Hider

### PR DESCRIPTION
**Pull request by rukemn**
Hint rating can now be tuned via Preference
Whether Hint or Treasure is picked first via Preference
Javadocs

Fixes #234
Fixes #284

### CODE REVIEW

File: src/main/java/com/treasure/hunt/jts/geom/GeometryAngle.java [hunk 1]
```diff
@@ -63,6 +64,17 @@ public GeometryAngle(GeometryFactory factory, Coordinate center, double start, d
         );
     }
 
+    /** the Angle between the middle of the Hint and the x axis normalized to the range of [0 , 2*PI]
+     *
+     * @return the angle in radians
+     */
+    public double getNormalizedAngle(){
+        double angle = Angle.angle(this.getCenter() , JTSUtils.middleOfGeometryAngle(this));
+        if( angle < 0){
```
Comment (DorianRec) [inline src/main/java/com/treasure/hunt/jts/geom/GeometryAngle.java]: Please use autoformatting, which prevents **many** merge conflicts in later merges.
This could be used by pressing Strg+Alt+l for one file.
Better tick all these: 
Bildschirmfoto 2020-03-29 um 18 13 44

**Review by DorianRec — CHANGES_REQUESTED** [review]

**Review by DorianRec — CHANGES_REQUESTED** [review]
Simulating this with NaiveAngleSearcher, MobileTreasureHider and GameEngine, i got the following (Seems that the MobileTreasureHider gives Hints, which not includes the treasure, look at the last lines of stacktraces!):

18:24:50.370 [JavaFX Application Thread] INFO  c.t.h.s.h.impl.MobileTreasureHider -  --- MOVE STARTED ---
18:24:50.372 [JavaFX Application Thread] DEBUG c.t.h.s.h.impl.MobileTreasureHider - treasure first, hint second
18:24:50.374 [JavaFX Application Thread] DEBUG c.t.h.strategy.hider.impl.GameField - best overall calculated constant is0.6585091911355823 at (99.351255546, -10.247478613, NaN)
18:24:50.374 [JavaFX Application Thread] INFO  c.t.h.s.h.impl.MobileTreasureHider - trying to move the Treasure to POINT (99.351255546 -10.247478613)
18:24:50.375 [JavaFX Application Thread] INFO  c.t.h.strategy.hider.impl.GameField - new treasure location atPOINT (99.351255546 -10.247478613)
18:24:50.375 [JavaFX Application Thread] INFO  c.t.h.s.hider.impl.StatisticalHider - generating 360 hints of size 180.0
18:24:50.377 [JavaFX Application Thread] INFO  c.t.h.s.hider.impl.StatisticalHider - current possibleArea size 1963.1512533607531
18:24:50.451 [JavaFX Application Thread] DEBUG c.t.h.s.hider.impl.StatisticalHider - remaining possible Hints180
18:24:50.451 [JavaFX Application Thread] INFO  c.t.h.s.hider.impl.StatisticalHider - angleHint with the best rating
18:24:50.451 [JavaFX Application Thread] INFO  c.t.h.s.hider.impl.StatisticalHider - Hint at (35.31232982088212, 4.746345622951012, NaN) with normal angle of6.000000000000123, absolute Area Cutoff=16.34699123250425, relative Area Cutoff= 0.008326913784416535, Centroid distance to Treasure = 33.48392993566115, NormalLine distance to Treasure = 21.605576993314855, WorstPoint is =(0.0, 0.0, NaN) with C= 0.0}
18:24:50.451 [JavaFX Application Thread] INFO  c.t.h.s.h.impl.MobileTreasureHider -  --- MOVE ENDED ---
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1787)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8865)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3876)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3604)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2613)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:395)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1782)
	... 45 more
Caused by: java.lang.IllegalArgumentException: Treasure does not lie in given Angle.
	at com.treasure.hunt.game.GameEngine.verifyHint(GameEngine.java:155)
	at com.treasure.hunt.game.GameEngine.hiderMove(GameEngine.java:125)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:113)
Caused by: java.lang.IllegalArgumentException: Treasure does not lie in given Angle.

	at com.treasure.hunt.game.GameManager.next(GameManager.java:168)
	at com.treasure.hunt.view.widget.NavigationController.nextButtonClicked(NavigationController.java:55)
	... 55 more

**Comment by rukemn** [comment]
"Treasure does not lie in given Angle. " 

This is not a bug caused by the hider, its from the GameEngine!

The GameEngine doesn#t check against the current target, but the initial one i think

File: src/main/java/com/treasure/hunt/jts/geom/GeometryAngle.java (hunk 1 above)
Comment (rukemn) [reply src/main/java/com/treasure/hunt/jts/geom/GeometryAngle.java]: Formatted

**Review by DorianRec — CHANGES_REQUESTED** [review]
Unfortunately, I got an Exception, simulating the NaiveAngleHintSearcher, FixedTreasureSearcher and GameEngine:

21:43:03.825 [JavaFX Application Thread] INFO  c.t.h.s.hider.impl.StatisticalHider - generating 360 hints of size 180.0
21:43:03.827 [JavaFX Application Thread] INFO  c.t.h.s.hider.impl.StatisticalHider - current possibleArea size 6366.047884012224
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1787)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8865)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3876)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3604)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2613)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:395)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Caused by: java.lang.reflect.InvocationTargetException

	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1782)
	... 45 more
Caused by: java.lang.IllegalArgumentException: Operation does not support GeometryCollection arguments
	at org.locationtech.jts.geom.Geometry.checkNotGeometryCollection(Geometry.java:1803)
	at org.locationtech.jts.geom.Geometry.union(Geometry.java:1386)
	at com.treasure.hunt.strategy.hider.impl.GameField.testHint(GameField.java:261)
Caused by: java.lang.IllegalArgumentException: Operation does not support GeometryCollection arguments

	at com.treasure.hunt.strategy.hider.impl.StatisticalHider.eval(StatisticalHider.java:96)
	at com.treasure.hunt.strategy.hider.impl.StatisticalHider.move(StatisticalHider.java:75)
	at com.treasure.hunt.strategy.hider.impl.FixedTreasureHider.move(FixedTreasureHider.java:13)
	at com.treasure.hunt.game.GameEngine.hiderMove(GameEngine.java:123)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:113)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:168)
	at com.treasure.hunt.view.widget.NavigationController.nextButtonClicked(NavigationController.java:55)
	... 55 more

**Review by DorianRec — CHANGES_REQUESTED** [review]
Simulating the StrategyFromPaper versous HalfPlaneAdapter_FixedTreasure, threw me the following on the 116. move, which could also be an error in the StrategyFromPaper.

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.treasure.hunt.strategy.searcher.impl.strategyFromPaper.LastHintBadSubroutine.lastHintBadSubroutine(LastHintBadSubroutine.java:356)
	at com.treasure.hunt.strategy.searcher.impl.strategyFromPaper.StrategyFromPaper.move(StrategyFromPaper.java:114)
	at com.treasure.hunt.strategy.searcher.impl.strategyFromPaper.StrategyFromPaper.move(StrategyFromPaper.java:33)
	at com.treasure.hunt.game.GameEngine.searcherMove(GameEngine.java:136)
	at com.treasure.hunt.game.GameEngine.move(GameEngine.java:107)
	at com.treasure.hunt.game.GameManager.next(GameManager.java:168)
	at com.treasure.hunt.game.GameManager.lambda$beat$10(GameManager.java:262)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by rukemn** [comment]
Fixed Issue 284, 
BadHintsubroutine is not caused by Statistical Hider I think

**Review by DorianRec — APPROVED** [review]
No errors found :)
