### PR TITLE
deserialization broken

### LINKED ISSUE #219: Critical bug between the collaboration between Preferences and Saved hunts.
How to reproduce:

* Do a first run and save it.
* Change the preferences (ideally, increase the Treasure distance by a large number)
* Load your first run
* Running it causes the searcher to go to the treasure, then the position of the treasure changes and the searcher continues searching the treasure.

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #219

### CODE REVIEW

File: src/main/java/com/treasure/hunt/game/GameManager.java [hunk 1]
```diff
@@ -112,7 +112,9 @@ public GameManager(Class<? extends Searcher> searcherClass, Class<? extends Hide
```
Comment (jotoh98) [inline src/main/java/com/treasure/hunt/game/GameManager.java:112]: javadoc missing

File: src/main/java/com/treasure/hunt/view/widget/HistoryController.java [hunk 2]
```diff
@@ -51,6 +51,8 @@ protected void updateItem(Turn turn, boolean empty) {
             }
         });
 
+        list.getSelectionModel().select(0);
```
Comment (jotoh98) [inline src/main/java/com/treasure/hunt/view/widget/HistoryController.java:54]: trick too cheap

**Review by jotoh98 — APPROVED** [review]
Y u no javadoc?
